# Generated by Django 2.1.5 on 2019-04-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190418_2318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guide_booking_model',
            unique_together=set(),
        ),
    ]
