# Generated by Django 2.1.5 on 2019-04-19 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190419_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_booking_model',
            name='tourist_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Tourist_Registration'),
        ),
    ]
