# Generated by Django 2.1.5 on 2019-04-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190419_0927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guide_booking_model',
            unique_together={('guide_username', 'date_field')},
        ),
    ]
