# Generated by Django 2.1.5 on 2019-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20190419_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_registration',
            name='Address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guide_registration',
            name='gender',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='guide_registration',
            name='native_place',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='tourist_registration',
            name='gender',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='tourist_registration',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
