# Generated by Django 2.1.5 on 2019-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20190421_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_registration',
            name='Address',
            field=models.CharField(max_length=50),
        ),
    ]
